/**
 * Honeydome API
 * Honeydome-Web 调用 Honeydome-Engine 的 API 的接口规约。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 用字符串键值对表示的单个参数项
 */
export interface Arg { 
    /**
     * 字符串表示的键
     */
    key?: string;
    /**
     * 用字符串表示的值
     */
    value?: string;
}

