/**
 * Honeydome API
 * Honeydome-Web 调用 Honeydome-Engine 的 API 的接口规约。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Config } from './config';
import { Page } from './page';


export interface ConfigListPage { 
    data?: Array<Config>;
    page?: Page;
}

