/**
 * Honeydome API
 * Honeydome-Web 调用 Honeydome-Engine 的 API 的接口规约。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 分页查询请求
 */
export interface Pageable { 
    page?: number;
    size?: number;
}

